import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Providers from '../providers'
import { getSession } from 'next-auth/react'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  // Providing all messages to the client
  // side is the easiest way to get started
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>

        <Providers>
          <div className='w-full'>
            <main className='mt-6 flex w-full flex-col items-center'>
              <div className='w-full max-w-[1024px] px-4 lg:px-8'>
                {children}
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
