const columns = [
    { name: "ID", uid: "id", sortable: true },
    { name: "NAME", uid: "name", sortable: true },
    { name: "SUBSCRIPTION PLAN", uid: "subscription_plan", sortable: true },
    { name: "BILLING CYCLE", uid: "billing_cycle" },
    { name: "DOMAIN NAME", uid: "domain_name" },
    { name: "STATUS", uid: "status", sortable: true },
    { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
    { name: "Active", uid: "active" },
    { name: "Paused", uid: "paused" },
    { name: "Suspended", uid: "suspended" },
];


const subscriptionPlanOptions = [
    { name: "Free Trial", uid: "free_trial" },
    { name: "Basic", uid: "basic" },
    { name: "Pro", uid: "pro" },
    { name: "Enterprise", uid: "enterprise" },
];
const subscriptionPlanCategory = [
    { name: "Entertainment", uid: "entertainment" },
    { name: "Business", uid: "business" },
    { name: "Education", uid: "education" },
    { name: "Health", uid: "health" },
    { name: "Finance", uid: "finance" },
    { name: "Technology", uid: "technology" },
    { name: "Travel", uid: "travel" },
    { name: "Ecommerce", uid: "ecommerce" },
    { name: "Service Booking", uid: "booking" },
    { name: "Real Estate", uid: "estate" },
    { name: "Food & Beverage", uid: "food" },
    { name: "Event Management", uid: "event" },
    { name: "Job Portal", uid: "job" },
    { name: "Dating", uid: "dating" },
    { name: "Gaming", uid: "gaming" },
    { name: "Other", uid: "other" },

]
const websites = [
    {
        id: 1,
        name: "TonyReichert.com",
        subscription_plan: "Pro",
        billing_cycle: "Monthly",
        domain_name: "tonyreichert.com",
        status: "active",
        subscription_plan_category: "Business",
        logo: "https://placehold.co/100x100/ff5733/ffffff?text=TonyReichert.com",
    },
    {
        id: 2,
        name: "ZoeyLang.dev",
        subscription_plan: "Basic",
        billing_cycle: "Yearly",
        domain_name: "zoeylang.dev",
        status: "paused",
        subscription_plan_category: "Technology",
        logo: "https://placehold.co/100x100/33c1ff/ffffff?text=ZoeyLang.dev",
    },
    {
        id: 3,
        name: "JaneFisher.io",
        subscription_plan: "Pro",
        billing_cycle: "Monthly",
        domain_name: "janefisher.io",
        status: "active",
        subscription_plan_category: "Ecommerce",
        logo: "https://placehold.co/100x100/ff33e6/ffffff?text=JaneFisher.io",
    },
    {
        id: 4,
        name: "WilliamHoward.org",
        subscription_plan: "Enterprise",
        billing_cycle: "Monthly",
        domain_name: "williamhoward.org",
        status: "suspended",
        subscription_plan_category: "Real Estate",
        logo: "https://placehold.co/100x100/33ff57/ffffff?text=WilliamHoward.org",
    },
    {
        id: 5,
        name: "KristenCopper.net",
        subscription_plan: "Pro",
        billing_cycle: "Monthly",
        domain_name: "kristencopper.net",
        status: "active",
        subscription_plan_category: "Finance",
        logo: "https://placehold.co/100x100/5733ff/ffffff?text=KristenCopper.net",
    },
    {
        id: 6,
        name: "BrianKim.co",
        subscription_plan: "Basic",
        billing_cycle: "Yearly",
        domain_name: "briankim.co",
        status: "active",
        subscription_plan_category: "Education",
        logo: "https://placehold.co/100x100/ff5733/ffffff?text=BrianKim.co",
    },
    {
        id: 7,
        name: "MichaelHunt.design",
        subscription_plan: "Pro",
        billing_cycle: "Monthly",
        domain_name: "michaelhunt.design",
        status: "paused",
        subscription_plan_category: "Entertainment",
        logo: "https://placehold.co/100x100/33c1ff/ffffff?text=MichaelHunt.design",
    },
    {
        id: 8,
        name: "SamanthaBrooks.hr",
        subscription_plan: "Enterprise",
        billing_cycle: "Monthly",
        domain_name: "samanthabrooks.hr",
        status: "active",
        subscription_plan_category: "Health",
        logo: "https://placehold.co/100x100/ff33e6/ffffff?text=SamanthaBrooks.hr",
    },
    {
        id: 9,
        name: "FrankHarrison.finance",
        subscription_plan: "Enterprise",
        billing_cycle: "Yearly",
        domain_name: "frankharrison.finance",
        status: "suspended",
        subscription_plan_category: "Finance",
        logo: "https://placehold.co/100x100/33ff57/ffffff?text=FrankHarrison.finance",
    },
    {
        id: 10,
        name: "EmmaAdams.ops",
        subscription_plan: "Pro",
        billing_cycle: "Monthly",
        domain_name: "emmaadams.ops",
        status: "active",
        subscription_plan_category: "Operations",
        logo: "https://placehold.co/100x100/5733ff/ffffff?text=EmmaAdams.ops",
    },
    {
        id: 11,
        name: "BrandonStevens.dev",
        subscription_plan: "Basic",
        billing_cycle: "Yearly",
        domain_name: "brandonstevens.dev",
        status: "active",
        subscription_plan_category: "Technology",
        logo: "https://placehold.co/100x100/ff5733/ffffff?text=BrandonStevens.dev",
    },
    {
        id: 12,
        name: "MeganRichards.product",
        subscription_plan: "Pro",
        billing_cycle: "Monthly",
        domain_name: "meganrichards.product",
        status: "paused",
        subscription_plan_category: "Product",
        logo: "https://placehold.co/100x100/33c1ff/ffffff?text=MeganRichards.product",
    },
    {
        id: 13,
        name: "OliverScott.security",
        subscription_plan: "Enterprise",
        billing_cycle: "Monthly",
        domain_name: "oliverscott.security",
        status: "active",
        subscription_plan_category: "Security",
        logo: "https://placehold.co/100x100/ff33e6/ffffff?text=OliverScott.security",
    },
    {
        id: 14,
        name: "GraceAllen.marketing",
        subscription_plan: "Basic",
        billing_cycle: "Yearly",
        domain_name: "graceallen.marketing",
        status: "active",
        subscription_plan_category: "Marketing",
        logo: "https://placehold.co/100x100/33ff57/ffffff?text=GraceAllen.marketing",
    },
    {
        id: 15,
        name: "NoahCarter.it",
        subscription_plan: "Pro",
        billing_cycle: "Monthly",
        domain_name: "noahcarter.it",
        status: "paused",
        subscription_plan_category: "IT",
        logo: "https://placehold.co/100x100/5733ff/ffffff?text=NoahCarter.it",
    },
    {
        id: 16,
        name: "AvaPerez.sales",
        subscription_plan: "Enterprise",
        billing_cycle: "Yearly",
        domain_name: "avaperez.sales",
        status: "active",
        subscription_plan_category: "Sales",
        logo: "https://placehold.co/100x100/ff5733/ffffff?text=AvaPerez.sales",
    },
    {
        id: 17,
        name: "LiamJohnson.analytics",
        subscription_plan: "Enterprise",
        billing_cycle: "Monthly",
        domain_name: "liamjohnson.analytics",
        status: "active",
        subscription_plan_category: "Analytics",
        logo: "https://placehold.co/100x100/33c1ff/ffffff?text=LiamJohnson.analytics",
    },
    {
        id: 18,
        name: "SophiaTaylor.testing",
        subscription_plan: "Basic",
        billing_cycle: "Monthly",
        domain_name: "sophiataylor.testing",
        status: "active",
        subscription_plan_category: "Testing",
        logo: "https://placehold.co/100x100/ff33e6/ffffff?text=SophiaTaylor.testing",
    },
    {
        id: 19,
        name: "LucasHarris.it",
        subscription_plan: "Pro",
        billing_cycle: "Yearly",
        domain_name: "lucasharris.it",
        status: "paused",
        subscription_plan_category: "IT",
        logo: "https://placehold.co/100x100/33ff57/ffffff?text=LucasHarris.it",
    },
    {
        id: 20,
        name: "MiaRobinson.ops",
        subscription_plan: "Enterprise",
        billing_cycle: "Monthly",
        domain_name: "miarobinson.ops",
        status: "active",
        subscription_plan_category: "Operations",
        logo: "https://placehold.co/100x100/5733ff/ffffff?text=MiaRobinson.ops",
    },
];

export { columns, websites, statusOptions, subscriptionPlanOptions, subscriptionPlanCategory };
