import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Providers from '@/app/providers'
import MyAccountNavbar from '@/app/components/myaccount/common/navbar'
import { auth } from '@/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {


  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <MyAccountNavbar />
          <div className='w-full'>
            <main className='mt-6 flex w-full flex-col items-center'>
              <div className='w-full max-w-[1024px] px-4 lg:px-8'>
                {children}
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
