import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Providers from '@/app/providers'
import MyAccountNavbar from '@/app/components/myaccount/common/navbar'
import { getSession } from 'next-auth/react'
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale();
  const messages = await getMessages();



  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={inter.className}>

        <Providers messages={messages} locale={locale}>
          <MyAccountNavbar />
          <div className='w-full'>
            <main className='mt-6 flex w-full flex-col items-center'>
              <div className='w-full max-w-[1440px] px-4 lg:px-8'>
                {children}
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
